### PR TITLE
Added new candidate name to GSoC list

### PR DESCRIPTION
**Pull request by anuditverma**
added my name to the GSoC candidates' list.

### CODE REVIEW

**Comment by tttp** [comment]
Hi, 

There is a merge conflict (with another student that was faster than you). Can you merge and solve on your side and commit again?

**Comment by anuditverma** [comment]
Hi,
I have made some changes to fix the merge conflict, please have a look.
Thanks.

**Comment by tttp** [comment]
Hi,

You haven't fixed the conflict: you have removed the name of the other student and put yours instead. The aim is to get both his and your name.

you have plenty of nice tutorials on how to handle merge conflicts with git, feel free to follow their suggestions, it's a fairly standard problem and it's well explained how to solve it.

X+

**Comment by anuditverma** [comment]
Sorry, my bad
I didn't see the other candidate's name.
Will post some new changes.
Thanks.

**Comment by anuditverma** [comment]
I hope it seems fine now. :innocent: 
Thank you.

**Comment by tttp** [comment]
"We can’t automatically merge this pull request."
you have now the correct content in the file, but you have still not told git that the conflict is resolved and that this file is the proper merged result. 

Can you try again and wrestle a bit more with git pull and git merge? 

at this point, might be easier to create a new branch from upstream master (from the one you forked) and rebase
http://git-scm.com/book/en/v2/Git-Branching-Rebasing

I know it's weird to have to struggle with git so much to add a single line, but keep in mind that it will happen too with real code, and that it will be harder to merge properly than with this single line issue

Good luck

**Comment by tttp** [comment]
Beware that you will need to do a new pull, as they have been more names added

**Comment by tttp** [comment]
Are you finding your way around git merge conflicts?

**Comment by anuditverma** [comment]
Hi,
Yes sir, I have gone through numerous tutorials and guides on solving git conflicts.I worked on git bash and learned how to keep the master branch clean and never make changes until it has been merged to the upstream master. I got the know how of doing rebasing a master and to checkout feature (or arbitrary branch), pulling origin master and further more I learned about resolving a removed file conflict.
I spent hours on this after encountering that merge conflict on this repo and thereafter when you advised me to go through such tutorials.
Thank you, I am very much delighted and glad to hear back from you. I am posting my progress updates on forum.civicrm.org I am feeling positive about getting some responses there also.

**Pull request closed without merging**
